"""
Find here all tense verben constante values

"""

from enum import Enum, unique


@unique
class GradePlayer(Enum):
    """
    Get the grade of the player
    """
    CREATOR = "GERMAN TENSE HAS NO SECRET FOR YOU ! YOU ARE THE PERFECTION IN HIS EYES !",
    MASTER = "GERMAN TENSE IS AS SIMPLE AS SAYING \"HELLO\" FOR YOU ! YOU CAN STOP HERE BUT REMEMBER: PERFECTION IS THE NEXT DOOR !",
    EXPERT = "GERMAN TENSE RECOGNISES YOU AS A SKILLFULL PERSON ! YOU ARE NOT FAR FROM PERFECTION !"
    ELITE = "GERMAN TENSE HAS ALREADY RECOGNISED YOU AS A GENIUS ! BUT THE ROAD IS STILL LONG TO REACH PERFECTION"
    DISCIPLE = "GERMAN TENSE HAS RECOGNISED YOUR POTENTIAL ! A LONG ROAD HIS WATING FOR YOU TO REACH THE PERFECTION !"
    OUTSIDER = "GERMAN TENSE HAS RECOGNISED YOU AS A POTENTIAL TALENT ! A LONG ROAD HIS WATING FOR YOU TO REACH THE PERFECTION !"
    ALIEN = "ERROR ERROR ERROR GERMAN TENSE DOES NOT RECOGNISE YOU ! PLEASE UPGRADE YOURSELF IF YOU WANT HIS RECOGNITION !"
